spring:
  application:
    name: simplify-tech-desafio
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: jdbc:mysql://${ENV_DATABASE_URL:localhost}:${ENV_DATABASE_PORT:3306}/tarefas?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_DATABASE_USERNAME:root}
    password: ${ENV_ROOT_DATABASE_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  threads:
    virtual:
      enabled: true
server:
  port: 8090
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20